{{if .Values.kafkaServiceAccount.enabled}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafkasa
  namespace: confluent
spec:
  encryptedData:
    basic.txt: AgA111AMxs7ALXCyq6NnHtj1OcPeIG5C9AkQE6Ouhx84SDVyUHlkXNwIlO7O/Ucf+yrTYoaHRLagCACGe4ODbKOnDb7nJg6wB8FoJmsWi3M12gf7e8/oUtZuM3THlT8xe0mMUL+6K3vdLCK5z2CD9b5GwKLrH2YaC4oPLJaWvEE0IWjd99nZJqG3QzzA80xJteDQVnw6eg6IeZiALV5Pun4/HMHXhWFXOGQc5Ca+NyZhxkoXa8/0zf8uXgl5DXHp4nW2R9YY+aUpIJtXuooOOsKLsxV0PmYY3o6KSH1/MUi5Mvlfuyn2pt2tcVx12c5VBiG63eHlTMBWHfd0N8ygDdiX+yKcUnM6/TGgtqgY+hFMVFx0EeDY8gYGkLVWZgciwxPP/xVV5alKRdSL8GDUiA9C5Rl/ol++5nc6Q/S7pMFEIA3qdSPqZ8cGZHwGtaE/ETt3SAFhjV8I0GCJp5HS8B8e7Piog2EWRD201hRleNAiuEfM9VMntmgztjIGAHvFF8Smt5/B90s20zfTn+qYt0nzdkKX+epWPG+OF3+egCVqzO7kDPUc6sFi0B1UD9yLlVZXMZVEHzcnjFkVJDkn2/AutuNnGOSSTODyWB2LprgYOkQ2bUABFzyHwa1Oy9dnoEKY5YdvSW9AGydHYZv0QgEb7y6HQW28cEoNLkH6qCoC5Rw0egWxpfKNfP+M8kuXppvmGN3QtDlPQHDfFCg/QyUiyBxAKAZClgy2vPzrYYlgq9VGpaS7i05JS3BzuXRXT5jDqB8XiUEBEANnwn9QbALqozo=  
    digest-users.json: AgBMF6jUy+WQ5siMC4xcFh+im117udoFV6J6RyHHHl0b4xuQhQrc9jzGIGRyfKZFffqcyOGLa+evRuYPyH/lWQdJD1by/JXe+rMv8Fw1ds6ZOsChhqxU71ZSdSGIT5zuZmqd2d0bj6HsaC6OmLlx++F0TPv/Y8TDAJI/hLKEV8E7AxrKqLVZ3kr44wX0JzPkz91+coStlLPhz+/DlJeWXfsyLk/UI7mT3shlDm0NYxe7In70FL/y0n7dusazLSOuODSSuQ1YebMHXGo3xMnZlNZYIjJMiI9CEhM2RQxrkUxGZ15odgEKwpKZ2rixn3Xh8xThTz90f846vh9XmPiOXcguk45lQrpMc/iqRg5rDKPMk/OIrn9VGqFnGGf+qsFpz6E1m8zwFJcjQAAtIdp+Uog9RfPHYyMIE1JbKmDEXkJS1eopSdFg2DtjUWfLzzlNP2oN2m2i1aQr2PxbpDLOh8JkQUjWg1Om7DlNoU0Sg7y7g6bAHKj5qeyKbbDC5yRMTGBNHgt6dLBAtdSq1z3OUdUEEc3tpkCA3vUvagmgCCnSGcVAMDlHN5aSx4fpU51RuCd8SegOr+WlXb+vtxg30tEmA9J0wBXE1/i5jPRCNrBNK/UWRR05sjp/lq/LPcSagR5xMg6s3wBT3kW/CGoRx5TwqVL6sWThj/T9mteFZmkAWwHBH+rLt06tD1gA5r9qvm6/7HNxF24XmcqgUiwElKz9GHRVzZ3z4GscdL6op6oJ  
    digest.txt: AgBVg0QgO1S3hGqzM1dtxkjZ6yUC7yA4DyZdgGEFe4XkA93e4o60FLDgZGOPZY5xdtQsl+l44KXvN2oYRac+saekh3OnWbOrizmx88bwGCdLDX8nxr62xNQuDJyqQuU4StLJG5l/e6LXxarHqjnEzaxbiQN1kmYc7wGUpdoaS77wQATwWSgTHdE5r5HANLrqcizY+rCsej4xqLG1ntq7NwvYdg7aw/Cn8ELS+MnlhoU+Bn9/ZYq6EhC/GtSv/mPe8Zs6icI6m7YOcGqoFYH7GIbNy9UXvngpq0xUcj8aBoSgHDmd6yCrmV6lxaLssYxl7a/GIIWRkC1prEE/BDepA4vAFTsHsI8zWn2OFQ3AyQCnzdKLUCeyozg4rYCTLRY8fg2j9KMZgu+ZlmafS5mxf/FkMztcWpsJCFk50sUE21eUYY1uE7fjRpLbTJkmp6M/PYDt0miGvC5TGweKYH1qgTlOqRRN0POAZD1qKZDt89kbqBBHzudVuQ/HBSLL+hrSTa4fmyAd4pqQk7oVDKZPe7i/R/Fr7o/wrr4LWwNjn1DTBi2kvNe0UzUvt6sjmlctCLCjGKI7FBYqpqJiTrm1AS0hmZNdQAdbIkjQh3a9GFe7svt6hHkiaj2MNfTkMNd+mM20dr3R1FdbCiCRHFFGUfcH78UypLzukYSwjSZRwgkpjDdQoMwsQHKk4PM+whvS/D+cTt1g74V4e+2jZmOdIoYR+5ImmOsddJb45Jtajx+SiYCpBdcOS39a
    plain.txt: AgBvOkTKKJ9wl0lqA7lYGqSvrcocvX11gKmTASZOMUNEKie1Q5oOihHkSURjk7p3WRcw/trVvRvWsoC0zJqPSLcJPe4MX78yzHZ+AQNdObcbXQg8GtkxutP6FfOhvl/ng+NBpxIZXAuQqIWGKuJrXkmXFvGHvhxuxaQYAbPkiScOMK2NnKDIa7rQ4TkDBBwBuYC4cyTv1QbWeMlDWDngK6ruY5vTHIAsvPbVuYPyUNbVI/aBa+/oWVHSDXdC6wZf7y+PsHklGzewmCgykhvfQsiVQIwTHKfAxRHGrJSNVyoXiF26dI0a1YtwkAjFjb/Lpe7456w5QJHQ69dd3nrdF/Y8FfwO5PWlQxd/vv1yNAzMLSYS7xiWy5KLf55/SvPQJJ3hqBSx6S+IGZQHCAu2Tz8VdEGpF+wJpRw8qXrR4wTofifbeWrcWpPSr/ayQVBWM1vTfJQmg6YEJVacP1ncnaNcGGll5DQZBlJpkuzyFllEAJ6V8dHPzoP3BQzylxgL78ni9lghldVs5TgNwPeJaNVfzyXDW4jTAGl4Hc0lqZF+l9L3EkRBlkki7MvwrmZm+HHeKuW2xC7e2jRcAvdfklO3MdyM9rPODAl9oCJ7F5I4KERRTcLi8Tw+VDEdcMbEIzPilBRBKE5kdtr7LYf3VQvZnrZPrnqmWgzMvIlxp33nc+a4Tx+XoGgoBvMYxj2G790Vj4dagysebUFzBktbNCykfQUyLQH0LOh20Q/JRVb9zpe5f74=
  {{- range .Values.serviceAccounts }}
    {{ .name }}: {{.secret}}
  {{- end}}
  template:
    metadata:
      name: kafkasa
      namespace: confluent
    data:
      plain-users.json: |
        {    
            {{- $first := true -}}
            {{- range $i :=  .Values.serviceAccounts -}}              
              {{- if $first -}}
                  {{- $first = false -}}
              {{- else -}}
                  ,
              {{- end -}}          
              "{{$i.name }}":{{`"{{- index .`}} "{{$i.name -}}"{{` -`}}{{`}}"`}}
            {{- end -}}
        }
{{ end }}